### ISSUE TITLE
Using iFacialMocap for tracking

### ISSUE THREAD

**Issue by crystall1nedev** [vcamapp/app#3]
Would it be possible to add support for the popular apps iFacialMocap or FaceMotion3D into this app for real-time face tracking? 

As a macOS and iOS developer, I can take a crack at it too - just unsure of where to begin if I were to.

**Comment by tattn** [comment]
It's a very good idea!
Currently, VCam is not able to accept motion data from external sources, and the source code for the tracking part is not open to the public.
I'd like to support these in the near future and would like to make the external integration part public so that I can accept PRs.

**Comment by tattn** [comment]
Hi, the latest version supported iFacialMocap!
https://github.com/vcamapp/app/releases/tag/0.8.3

How to use (English subs available):
https://youtu.be/F8Oa0lNz9BY
