### ISSUE TITLE
[Feature request] Adjust z-axis

### ISSUE THREAD

**Issue by cccntu** [vcamapp/app#8]
Hi, 

Thanks for the app. I like it as a Mocopi front end on Mac. 
But when I use Mocopi the avatar is usually too close to the camera to show the full body.
Is there a way to move the avatar further away from the camera?

**Comment by tattn** [comment]
Thank you your feedback!

VCam has the function to move the camera.
When the avatar is selected and has a yellow border, scroll the mouse or trackpad to adjust the z-axis.

However, there is currently a limitation when using mocopi: depending on the avatar type, there may be problems with the avatar rendering.

**Comment by cccntu** [comment]
Ah I didn't try that, it works! Thank you for your reply!
